Drop in a ZK dependency to deal with dependency issues I was having
With ZK 3.4.6 which was the default dependency we were pulling in before this
would happen:

   java.lang.NoClassDefFoundError: org/apache/zookeeper/Watcher
       at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
       at java.lang.Class.privateGetPublicMethods(Class.java:2894)
       at java.lang.Class.getMethods(Class.java:1607)
       at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:46)
       at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:33)
       at org.codehaus.groovy.classgen.asm.BytecodeHelper.box(BytecodeHelper.java:602)
       at offtopic.curator.CuratorClient.<init>(CuratorClient.groovy:14)
       at offtopic.curator.CuratorClientInitializationSpec.with a valid String(CuratorClientSpec.groovy:23)
   Caused by: java.lang.ClassNotFoundException: org.apache.zookeeper.Watcher
       at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
       at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
       at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
       ... 8 more